### PR TITLE
C++20 support

### PR DESCRIPTION
**Pull request by chris-durand**
**AVR port of libstdc++ from gcc 10.2**

This was started almost from scratch because a lot has changed between versions 8 and 10 and old patches did not apply cleanly.

I included all provided headers in a modm example and the code compiled. Now also `std::map` and `std::list` work which caused a linker error beforehand, as I figured out today. Implementation source files have been missing. More AVR C++ examples will have to be added to modm to make sure it really works.

Basically, all things depending on a hosted OS and unsupported features on AVR (exceptions, rtti, atomics) have been removed.
As before, every standard library function that throws triggers a weakly-linked assertion handler instead, which is overridden in modm.

This gcc 10.2 version might not be compatible to earlier versions of gcc, I haven't done any tests. I don't think it is a big deal since modm itself will require avr-gcc 10 soon.

Since I don't have access to any AVR boards right now, I would need some help with testing @salkinium @rleh

- [x] Port libstdc++
- [x] Test on real hardware
Will be moved to different PR:
- [ ] ~~Document what is actually available~~
- [ ] ~~Add more examples to modm for better testing what actually works~~

### CODE REVIEW

**Comment by salkinium** [comment]
Thank you very much for this work! I have a ATmega328p I can test this on, as soon as I find my programmer for it. It's definitely here somewhere…

**Comment by salkinium** [comment]
I'm an idiot, I forgot this has a bootloader.

The vector example works:
```
AVR libstdc++ vector test

1 2 3 4
```
Here is the [macOS avr-gcc v10 hex file](https://github.com/modm-io/avr-libstdcpp/files/5742793/vector-test.txt) for you to compare with your avr-gcc v10 on Linux. If this differs, send me your hex file and I'll run it here.

**Comment by salkinium** [comment]
Slightly off-topic: Do you think your modified libstdc++ could also be used on Cortex-M as is?

I'm planning to replace Newlib libc with the Picolibc libc and perhaps modularize it via lbuild to allow for replacing parts of it with a modm compatible version (for example, redirecting calls to vanilla `printf()`).
However, I've noticed that the stdlibc++ that comes with arm-none-eabi-gcc is compiled *with* exceptions, thus any exception raised in stdlibc++ will do something… weird? It would thus be useful to also compile stdlibc++ for Cortex-M and reuse this work for it.

**Comment by chris-durand** [comment]
@salkinium Thanks for testing, I should have an ATmega2560 board by Tuesday and can continue testing.

> Do you think your modified libstdc++ could also be used on Cortex-M as is?

It would probably run as is because everything requiring special hardware support was removed but I would advise against doing so. Everything has been removed which could cause problems on avr like atomics; things have been hacked to make it compile despite the lack of a proper C99 standard library, etc. 

The idea was to have some useful parts working on avr with low effort, not to create a proper C++ standard library.

>  However, I've noticed that the stdlibc++ that comes with arm-none-eabi-gcc is compiled with exceptions, thus any exception raised in stdlibc++ will do something… weird? It would thus be useful to also compile stdlibc++ for Cortex-M and reuse this work for it.

That is a bit concerning. At least most of the things in the standard library are templates defined in headers and not pre-compiled. 
I am not sure someone what could all throw from the compiled libraries. You could compile an unmodified libstdc++ yourself or do a version with less invasive modifications, if required.

**Comment by chris-durand** [comment]
There is still a problem with math functions intrduced with [0b07c90a](https://github.com/modm-io/avr-libstdcpp/commit/0b07c90a0792404ae923d30627422ef73b41017e).

With `__CORRECT_ISO_CPP_MATH_H_PROTO` being defined, calling a lot of math functions causes an endless recursion.
```
#ifndef __CORRECT_ISO_CPP_MATH_H_PROTO
  inline _GLIBCXX_CONSTEXPR float
  atan2(float __y, float __x)
  { return __builtin_atan2f(__y, __x); }

  inline _GLIBCXX_CONSTEXPR long double
  atan2(long double __y, long double __x)
  { return __builtin_atan2l(__y, __x); }
#endif

  template<typename _Tp, typename _Up>
    inline _GLIBCXX_CONSTEXPR
    typename __gnu_cxx::__promote_2<_Tp, _Up>::__type
    atan2(_Tp __y, _Up __x)
    {
      typedef typename __gnu_cxx::__promote_2<_Tp, _Up>::__type __type;
      return atan2(__type(__y), __type(__x));
    }
```

When only the third overload is defined in cmath it calls itself. Unfortunately we have to define the float variants (sinf, atan2f) as real functions to resolve the linker error, (they are macros in avr-libm :crying_cat_face: ).

**Comment by chris-durand** [comment]
The mentioned math function issue should be resolved. There are still missing math functions that will trigger a linker error because implementations don't exist in the AVR C standard library.

**Comment by chris-durand** [comment]
Tested in hardware, see modm C++20 PR. Documentation and examples will be done in a different PR. This has to be merged now to fix modm.

**Review by salkinium — APPROVED** [review]
Thanks a lot!

**Pull request merged**
